/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhougang_camera2encode_H264Encoder */

#ifndef _Included_com_zhougang_camera2encode_H264Encoder
#define _Included_com_zhougang_camera2encode_H264Encoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhougang_camera2encode_H264Encoder
 * Method:    encodeInitial
 * Signature: (IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_zhougang_camera2encode_H264Encoder_encodeInitial
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     com_zhougang_camera2encode_H264Encoder
 * Method:    videoEncode
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_zhougang_camera2encode_H264Encoder_videoEncode
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_zhougang_camera2encode_H264Encoder
 * Method:    flush
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zhougang_camera2encode_H264Encoder_flush
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
